In [2]:
import pandas as pd
import numpy as np
import random

In [43]:
a=random.randint(1,100)
a

55

In [44]:
a=[1,3,4,5,5,7,9,2,11]
a

[1, 3, 4, 5, 5, 7, 9, 2, 11]

In [45]:
a.append("new")
a

[1, 3, 4, 5, 5, 7, 9, 2, 11, 'new']

In [46]:
a.extend([23,34,3])

In [47]:
a

[1, 3, 4, 5, 5, 7, 9, 2, 11, 'new', 23, 34, 3]

In [48]:
a.extend([[23,34,3]])

In [49]:
a

[1, 3, 4, 5, 5, 7, 9, 2, 11, 'new', 23, 34, 3, [23, 34, 3]]

In [50]:
a.pop(3) # 3.değeri çıkartıyor.

5

In [51]:
a

[1, 3, 4, 5, 7, 9, 2, 11, 'new', 23, 34, 3, [23, 34, 3]]

In [52]:
del(a[5]) 

In [53]:
a

[1, 3, 4, 5, 7, 2, 11, 'new', 23, 34, 3, [23, 34, 3]]

In [54]:
a[5]=9
a

[1, 3, 4, 5, 7, 9, 11, 'new', 23, 34, 3, [23, 34, 3]]

In [55]:
del(a[7::])

In [56]:
sorted(a)

[1, 3, 4, 5, 7, 9, 11]

In [57]:
sorted(a, reverse=True)

[11, 9, 7, 5, 4, 3, 1]

In [58]:
text=["Happy birth day"]
text

['Happy birth day']

In [59]:
"Happy birth day".split(" ")

['Happy', 'birth', 'day']

In [60]:
text[0].split()

['Happy', 'birth', 'day']

## SET

In [61]:
country_sets=["nl", "usa", "uk", "uk"]
country_sets=set(sets)
country_sets

{'nl', 'uk', 'usa'}

In [62]:
country_sets.add("ger")
country_sets

{'ger', 'nl', 'uk', 'usa'}

In [63]:
country_sets.remove("ger")
country_sets

{'nl', 'uk', 'usa'}

In [64]:
print(type(country_sets))

<class 'set'>


In [65]:
"nl" in country_sets

True

In [72]:
city_set={"london", "amsterdam", "paris", "New York", "nl"}
city_set

{'New York', 'amsterdam', 'london', 'nl', 'paris'}

In [77]:
place= country_sets & city_set # kesişim intersection in diagram
place

{'nl'}

In [78]:
place1= country_sets | city_set  # birleşim
place1

{'New York', 'amsterdam', 'london', 'nl', 'paris', 'uk', 'usa'}

In [80]:
place_union= country_sets.union(city_set) # birleşim
place_union

{'New York', 'amsterdam', 'london', 'nl', 'paris', 'uk', 'usa'}

In [81]:
place_intersection= country_sets.intersection(city_set) # kesişim
place_intersection

{'nl'}

In [82]:
place_intersection= country_sets.difference(city_set) # fark
place_intersection

{'uk', 'usa'}

In [10]:
X=np.array([[1,0,1],[2,2,2]]) 
out=X[0:2,2]
out

array([1, 2])

In [9]:

X=np.array([[1,0,1],[2,2,2]]) 
out=X[0:2,2]
out


array([1, 2])

In [6]:
X=np.array([[1,0],[0,1]])
Y=np.array([[2,2],[2,2]])
Z=np.dot(X,Y)
Z

array([[2, 2],
       [2, 2]])

In [8]:
a=np.array([0,1])
b=np.array([1,0])
np.dot(a,b) 

0

In [7]:
a=np.array([-1,1])
b=np.array([1,1])
np.dot(a,b) 

0

In [5]:
serie1 = pd.Series(list('abcedfghijklmnopqrstuvwxyz'))
serie1

0     a
1     b
2     c
3     e
4     d
5     f
6     g
7     h
8     i
9     j
10    k
11    l
12    m
13    n
14    o
15    p
16    q
17    r
18    s
19    t
20    u
21    v
22    w
23    x
24    y
25    z
dtype: object

In [6]:
serie2 = pd.Series(np.arange(26))
serie2 

0      0
1      1
2      2
3      3
4      4
5      5
6      6
7      7
8      8
9      9
10    10
11    11
12    12
13    13
14    14
15    15
16    16
17    17
18    18
19    19
20    20
21    21
22    22
23    23
24    24
25    25
dtype: int32

In [16]:
clist = ['make','model', 'age', 'km','Gearing_Type', 'price']
df= df[clist]

AttributeError: 'Series' object has no attribute 'join'

In [20]:
df=pd.concat([serie1,serie2], axis=1)
df.rename(columns={0: "letter", 1: "number"}, inplace=True)
df

letter  number
0       a       0
1       b       1
2       c       2
3       e       3
4       d       4
5       f       5
6       g       6
7       h       7
8       i       8
9       j       9
10      k      10
11      l      11
12      m      12
13      n      13
14      o      14
15      p      15
16      q      16
17      r      17
18      s      18
19      t      19
20      u      20
21      v      21
22      w      22
23      x      23
24      y      24
25      z      25

In [21]:
ser1 = pd.Series([1, 2, 3, 4, 5])
ser2 = pd.Series([4, 5, 6, 7, 8])

In [22]:
set(ser1).difference(set(ser2))

{1, 2, 3}

In [31]:
set(ser1).symmetric_difference(set(ser2))

{1, 2, 3, 6, 7, 8}

In [43]:
name=["Vinay", "Kushal", "Aman","Rahul", "Ramesh"], 
occ= ["engineer", "doctor", "engineer", "doctor", "doctor"]
salary=[60000, 70000,50000,60000,65000]
df=pd.DataFrame([name,occ,salary])
df

0       1         2       3       4
0  [Vinay, Kushal, Aman, Rahul, Ramesh]    None      None    None    None
1                              engineer  doctor  engineer  doctor  doctor
2                                 60000   70000     50000   60000   65000

In [56]:
my_list= {"name": ["Vinay", "Kushal", "Aman","Rahul", "Ramesh"],\
        "occ": ["engineer", "doctor", "engineer", "doctor", "doctor"],\
        "salary": [60000, 70000,50000,60000,65000]}
my_list=pd.DataFrame(my_list)
my_list

name       occ  salary
0   Vinay  engineer   60000
1  Kushal    doctor   70000
2    Aman  engineer   50000
3   Rahul    doctor   60000
4  Ramesh    doctor   65000

In [ ]:
.groupby(["sex","pclass"])[["survived"]].mean()

In [57]:
my_list.groupby("occ")[["salary"]].mean()

salary
occ              
doctor    65000.0
engineer  55000.0